// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnMr60_Xnpu7C3H3cZKqs800qiiBM83Q4',
    appId: '1:197161488651:web:50c22b3fae34f7f8b3d20e',
    messagingSenderId: '197161488651',
    projectId: 'real-time-chat-app-5f7ba',
    authDomain: 'real-time-chat-app-5f7ba.firebaseapp.com',
    storageBucket: 'real-time-chat-app-5f7ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0SiX1bsUGwulOtJke9SPcvy5h1eyHrIE',
    appId: '1:197161488651:android:c64354168b983a20b3d20e',
    messagingSenderId: '197161488651',
    projectId: 'real-time-chat-app-5f7ba',
    storageBucket: 'real-time-chat-app-5f7ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNC6VVS5qex6Poul_TjLjxmH4cjW1zsgE',
    appId: '1:197161488651:ios:db8b987fe0a3fda0b3d20e',
    messagingSenderId: '197161488651',
    projectId: 'real-time-chat-app-5f7ba',
    storageBucket: 'real-time-chat-app-5f7ba.appspot.com',
    androidClientId: '197161488651-sp68q2ndma24ar76d643vbn0nlvh9aho.apps.googleusercontent.com',
    iosClientId: '197161488651-gasv2el86tvdhr3p46tenccci4qq20ms.apps.googleusercontent.com',
    iosBundleId: 'com.emincingoz.realtime-chat-app',
  );
}
